// import Navbar from './components/navbar'
import Navbar from './components/nav'
import './globals.css'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'

import { Inter } from 'next/font/google'
import Wrapper from '@/context/wrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Wrapper>{children}</Wrapper>
			</body>
		</html>
	)
}
