import React from 'react'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import Balancer from 'react-wrap-balancer'

const PrivacyPlicy = () => {
	return (
		<>
			<Navbar />
			<div className="bg-gradient-to-l mt-20 to-zicta-blue from-[#7CA5B8]  w-full flex-col bg-cover  h-full sm:min-h-[400px] min-h-[200px]  mb-20 flex items-center justify-center">
				<h1 className="sm:text-4xl text-2xl  text-white font-medium">
					<Balancer>Privacy Policy</Balancer>
				</h1>
				<p className="max-w-4xl mt-5 text-xs md:text-lg text-white">
					<Balancer></Balancer>
				</p>
			</div>
			<div className="min-h-screen py-20 h-full space-y-4 w-5/6 mx-auto">
				<h2 className="text-xl font-black text-zicta-blue">Privacy Policy</h2>
				<p>Last updated: September 21, 2023</p>
				<p>
					This Privacy Policy describes Our policies and procedures on the
					collection, processing, use and disclosure of Your information when
					You use the Service and tells You about Your privacy rights and how
					the law protects You.
				</p>
				<p>
					We use Your Personal data to provide and improve the Service. By using
					the Service, You agree to the collection, processing and use of
					information in accordance with this Privacy Policy. This Privacy
					Policy has been created with the help of the Free Privacy Policy
					Generator.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Interpretation and Definitions
				</h2>
				<h2 className="text-xl font-black text-zicta-blue">Interpretation</h2>
				<p>
					The words of which the initial letter is capitalized have meanings
					defined under the following conditions. The following definitions
					shall have the same meaning regardless of whether they appear in
					singular or in plural.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">Definitions</h2>
				<p>For the purposes of this Privacy Policy:</p>
				<div className="space-y-2">
					<p>
						<span className="font-bold">Account</span> means a unique account
						created for You to access our Service or parts of our Service.
					</p>
					<p>
						<span className="font-bold">Application</span> refers to ZICTA
						Digital Financial Services Incident Reporting System, the software
						program provided by the Authority.
					</p>
					<p>
						<span className="font-bold">Authority</span> referred to as either
						"the Authority", "We", "Us" or "Our" in this Agreement) refers to
						the Zambia Information and Communications Technology Authority,
						Stand No. 4909 Corner of Independence Avenue & United Nations Road.
					</p>
					<p>
						<span className="font-bold">Country</span> refers to: Zambia.
					</p>
					<p>
						<span className="font-bold">Device</span> means any device that can
						access the Service such as a computer, a cellphone or a digital
						tablet.
					</p>
					<p>
						<span className="font-bold">Personal Data</span> is any information
						that relates to an identified or identifiable individual.
					</p>
					<p>
						<span className="font-bold">Service</span> refers to the
						Application.
					</p>
					<p>
						<span className="font-bold">Service Provider</span> means any
						natural or legal person who processes the data on behalf of the
						Authority. It refers to third-party companies or individuals
						employed by the Authority to facilitate the Service, to provide the
						Service on behalf of the Authority, to perform services related to
						the Service or to assist the Authority in analyzing how the Service
						is used.
					</p>
					<p>
						<span className="font-bold">Usage Data</span> refers to data
						collected automatically, either generated by the use of the Service
						or from the Service infrastructure itself (for example, the duration
						of a page visit).
					</p>
					<p>
						<span className="font-bold">You</span> means the individual
						accessing or using the Service, or other legal entity on behalf of
						which such individual is accessing or using the Service,
					</p>
				</div>
				<h2 className="text-xl font-black text-zicta-blue">
					Collecting and Using Your Personal Data
				</h2>
				<h2 className="text-xl font-black text-zicta-blue">
					Types of Data Collected
				</h2>
				<h2 className="text-xl font-black text-zicta-blue">Personal Data</h2>
				<p>
					While using Our Service, We may ask You to provide Us with certain
					personal identifiable information that can be used to contact or
					identify You. Personal identifiable information may include, but is
					not limited to:
				</p>
				<ul className="list-disc px-10">
					<li>
						<p>Email address</p>
					</li>
					<li>First name and last name</li>
					<li>Phone number</li>
					<li>Address, State, Province, District, City</li>
					<p>Usage Data</p>
				</ul>
				<h2 className="text-xl font-black text-zicta-blue">Usage Data</h2>
				<p>Usage Data is collected automatically when using the Service.</p>
				<p>
					Usage Data may include information such as Your Device's Internet
					Protocol address (e.g., IP address), browser type, browser version,
					the pages of our Service that You visit, the time and date of Your
					visit, the time spent on those pages, unique device identifiers and
					other diagnostic data. <br />
					When You access the Service by or through a mobile device, We may
					collect certain information automatically, including, but not limited
					to, the type of mobile device You use, Your mobile device unique ID,
					the IP address of Your mobile device, Your mobile operating system,
					the type of mobile Internet browser You use, unique device identifiers
					and other diagnostic data.
					<br /> We may also collect information that Your browser sends
					whenever You visit our Service or when You access the Service by or
					through a mobile device.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Use of Your Personal Data
				</h2>
				<p>The Authority may use Personal Data for the following purposes:</p>
				<div className="w-5/6 mx-auto space-y-2">
					<p>
						<span className="font-bold">
							{' '}
							To provide and maintain our Service
						</span>
						, including to monitor the usage of our Service.
					</p>
					<p>
						<span className="font-bold"> To manage Your Account:</span>to manage
						Your registration as a user of the Service. The Personal Data You
						provide can give You access to different functionalities of the
						Service that are available to You as a registered user.
					</p>
					<p>
						<span className="font-bold">
							{' '}
							For the performance of a contract:
						</span>
						the development, compliance and undertaking of the purchase contract
						for the products, items or services You have purchased or of any
						other contract with Us through the Service.
					</p>
					<p>
						<span className="font-bold"> To contact You:</span>To contact You by
						email, telephone calls, SMS, or other equivalent forms of electronic
						communication, such as a mobile application's push notifications
						regarding updates or informative communications related to the
						functionalities, products or contracted services, including the
						security updates, when necessary or reasonable for their
						implementation.
					</p>
					<p>
						<span className="font-bold"> To provide You:</span>with news,
						special offers and general information about other goods, services,
						and events which we offer that are similar to those that you have
						already purchased
					</p>
					<p>
						<span className="font-bold"> To manage Your requests:</span>To
						attend and manage Your requests to Us.
					</p>
					<p>
						<span className="font-bold"> For other purposes:</span>We may use
						Your information for other purposes, such as data analysis,
						identifying usage trends, determining the effectiveness of our
						promotional campaigns and to evaluate and improve our Service,
						products, services, marketing and your experience.
					</p>
				</div>
				<p>
					We may share Your personal information in the following situations:
				</p>
				<ul className="list-disc px-10">
					<li>
						<span className="font-bold">With Service Providers:</span> We may
						share Your personal information with Service Providers to monitor
						and analyze the use of our Service, to contact You.
					</li>
					<li>
						<span className="font-bold">For Business transfers:</span> We may
						share or transfer Your personal information in connection with, or
						during negotiations of, any merger, sale of Company assets,
						financing, or acquisition of all or a portion of our business to
						another company.
					</li>
					<li>
						<span className="font-bold">With business partners:</span>
						We may share Your information with Our business partners to offer
						You certain products, services or promotions.
					</li>
					<li>
						<span className="font-bold">With other users:</span> when You share
						personal information or otherwise interact in the public areas with
						other users, such information may be viewed by all users and may be
						publicly distributed outside.
					</li>
				</ul>
				<p>
					<span className="font-bold">For other purposes:</span> By using this
					service, consumers consent to the Authority processing their personal
					information and the use of the information for any other purpose that
					is connected with the service.
				</p>
				<h3>Retention of Your Personal Data</h3>
				<p>
					The Authority will retain Your Personal Data only for as long as is
					necessary for the purposes set out in this Privacy Policy. We will
					retain and use Your Personal Data to the extent necessary to comply
					with our legal obligations (for example, if we are required to retain
					your data to comply with applicable laws), resolve disputes, and
					enforce our legal agreements and policies.
					<br />
					The Authority will also retain Usage Data for internal analysis
					purposes. Usage Data is generally retained for a shorter period of
					time, except when this data is used to strengthen the security or to
					improve the functionality of Our Service, or We are legally obligated
					to retain this data for longer time periods.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Transfer of Your Personal Data
				</h2>
				<p>
					perating offices and in any other places where the parties involved in
					the processing are located. It means that this information may be
					transferred to — and maintained on — computers located outside of Your
					state, province, country or other governmental jurisdiction where the
					data protection laws may differ than those from Your jurisdiction.
					<br />
					Your consent to this Privacy Policy followed by Your submission of
					such information represents Your agreement to that transfer. <br />
					The Authority will take all steps reasonably necessary to ensure that
					Your data is treated securely and in accordance with this Privacy
					Policy.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Delete Your Personal Data
				</h2>
				<p>
					You have the right to delete or request that We assist in deleting the
					Personal Data that We have collected about You. <br />
					Our Service may give You the ability to delete certain information
					about You from within the Service. <br />
					You may update, amend, or delete Your information at any time by
					signing in to Your Account, if you have one, and visiting the account
					settings section that allows you to manage Your personal information.
					You may also contact Us to request access to, correct, or delete any
					personal information that You have provided to Us. <br />
					Please note, however, that We may need to retain certain information
					when we have a legal obligation or lawful basis to do so.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Disclosure of Your Personal Data
				</h2>
				<h2 className="text-xl font-black text-zicta-blue">
					Business Transactions
				</h2>
				<p>
					If the Authority is involved in a merger, acquisition or asset sale,
					Your Personal Data may be transferred. We will provide notice before
					Your Personal Data is transferred and becomes subject to a different
					Privacy Policy.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">Law enforcement</h2>
				<p>
					Under certain circumstances, the Authority may be required to disclose
					Your Personal Data if required to do so by law or in response to valid
					requests by public authorities (e.g. a court or a government agency).
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Other legal requirements
				</h2>
				<p>
					The Authority may disclose Your Personal Data in the good faith belief
					that such action is necessary to:
				</p>
				<ul className="list-disc px-10">
					<li>Comply with a legal obligation</li>
					<li>Protect and defend the rights or property of the Authority</li>
					<li>
						Prevent or investigate possible wrongdoing in connection with the
						Service
					</li>
					<li>
						Protect the personal safety of Users of the Service or the public
					</li>
					<li>Protect against legal liability</li>
				</ul>
				<h2 className="text-xl font-black text-zicta-blue">
					Security of Your Personal Data
				</h2>
				<p>
					The security of Your Personal Data is important to Us, but remember
					that no method of transmission over the Internet, or method of
					electronic storage is 100% 6 secure. While We strive to use
					commercially acceptable means to protect Your Personal Data, We cannot
					guarantee its absolute security.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Children's Privacy
				</h2>
				<p>
					Our Service does not address anyone under the age of 13. We do not
					knowingly collect personal identifiable information from anyone under
					the age of 13. If You are a parent or guardian and You are aware that
					Your child has provided Us with Personal Data, please contact Us. If
					We become aware that We have collected Personal Data from anyone under
					the age of 13 without verification of parental consent, We take steps
					to remove that information from Our servers. <br />
					If We need to rely on consent as a legal basis for processing Your
					information and Your country requires consent from a parent, We may
					require Your parent's consent before We collect and use that
					information.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Links to Other Websites
				</h2>
				<p>
					Our Service may contain links to other websites that are not operated
					by Us. If You click on a third party link, You will be directed to
					that third party's site. We strongly advise You to review the Privacy
					Policy of every site You visit. <br />
					We have no control over and assume no responsibility for the content,
					privacy policies or practices of any third party sites or services.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">
					Changes to this Privacy Policy
				</h2>
				<p>
					We may update Our Privacy Policy from time to time. We will notify You
					of any changes by posting the new Privacy Policy on this page. <br />
					We will let You know via email and/or a prominent notice on Our
					Service, prior to the change becoming effective and update the "Last
					updated" date at the top of this Privacy Policy. <br />
					You are advised to review this Privacy Policy periodically for any
					changes. Changes to this Privacy Policy are effective when they are
					posted on this page.
				</p>
				<h2 className="text-xl font-black text-zicta-blue">Contact Us</h2>
				<p>
					If you have any questions about this Privacy Policy, You can contact
					us:
				</p>
				<ul className="list-disc px-10">
					<li>By email: info@zicta.zm</li>
				</ul>
			</div>
			<Footer />
		</>
	)
}

export default PrivacyPlicy
